const RepositoryActionTypes = {
  FETCH_REPOSITORY_START: 'FETCH_REPOSITORY_START',
  FETCH_REPOSITORY_SUCCESS: 'FETCH_REPOSITORY_SUCCESS',
  FETCH_REPOSITORY_FAILURE: 'FETCH_REPOSITORY_FAILURE',
  SET_NAME_SEARCH: 'SET_NAME_SEARCH',
  SET_LANGUAGE_SEARCH: 'SET_LANGUAGE_SEARCH'
};

export default RepositoryActionTypes;