const RepositoryActionTypes = {
  FETCH_REPOSITORY_START: 'FETCH_REPOSITORY_START',
  FETCH_REPOSITORY_SUCCESS: 'FETCH_REPOSITORY_SUCCESS',
  FETCH_REPOSITORY_FAILURE: 'FETCH_REPOSITORY_FAILURE',
  SET_NAME_SEARCH: 'SET_NAME_SEARCH',
  SET_LANGUAGE_SEARCH: 'SET_LANGUAGE_SEARCH',
  SET_SEARCH_ORDER: 'SET_SEARCH_ORDER',
  SET_PAGE_INDEX: 'SET_PAGE_INDEX'
};

export default RepositoryActionTypes;